M48
; DRILL file KiCad 10.0.5 date 2026-08-08T00:43:40
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-08T00:43:40+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X100.11Y-104.6
X105.89Y-104.6
T2
X14.0Y-14.0
X14.0Y-106.0
X115.0Y-35.0
X136.0Y-106.0
M30
