M48
; DRILL file KiCad 10.0.5 date 2026-08-07T14:54:16
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-07T14:54:16+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X72.11Y-74.6
X77.89Y-74.6
T2
X14.0Y-14.0
X14.0Y-76.0
X116.0Y-14.0
X116.0Y-76.0
M30
